//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WebServer_GUI.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_WEBSERVERGUI_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_WEBSERVERGUI			107
#define IDI_SMALL				108
#define IDC_WEBSERVERGUI			109
#define IDC_EDIT_TEXT_STATIC_ADMIN_MANAGEMENT 110
#define IDC_EDIT_TEXT_STATIC_NAME_OF_LIST 111
#define IDC_LIST 112
#define IDC_BUTTON_LIST_HISTORY 113
#define IDC_BUTTON_LIST_ACCOUNT 114
#define IDC_BUTTON_ADD 115
#define IDC_BUTTON_DELETE 116
#define IDC_EDIT_TEXT_USER 117
#define IDC_EDIT_TEXT_PASSWORD 118
#define IDC_EDIT_TEXT_NAME 119
#define IDC_BUTTON_ADD_SUBMIT 120
#define IDC_BUTTON_ADD_BACK 121
#define IDC_EDIT_TEXT_STATIC_ADD_STATUS 122
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
